extends RefCounted
class_name LegalContent

const EFFECTIVE_DATE := "11/09/2026"

const DOCUMENTS := {
	"es": {
		"privacy_title": "POLÍTICA DE PRIVACIDAD",
		"privacy_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nVigente desde: 11/09/2026",
		"privacy_sections": [
			{"title": "1. RESPONSABLE Y ALCANCE", "body": "ILLU ENTERTAINMENT desarrolla Satoshi Maze. Esta política explica qué información maneja esta versión de la aplicación y cómo se utiliza. Para consultas de privacidad, utilizá el canal de soporte publicado en la ficha oficial de la tienda desde la que descargaste la aplicación."},
			{"title": "2. DATOS GUARDADOS EN TU DISPOSITIVO", "body": "El juego guarda localmente progreso, estrellas, récords, Ghost Runs, ajustes, idioma, estadísticas, cosméticos, productos adquiridos y un historial local de compras. También genera un identificador aleatorio de instalación para funciones de perfil y ranking. Ese identificador no se obtiene del IMEI, número de teléfono, contactos ni otros identificadores del sistema."},
			{"title": "3. PAGOS LIGHTNING", "body": "Cuando iniciás una compra, Satoshi Maze se comunica por HTTPS con el proveedor Lightning/LNURL-pay configurado para crear y verificar una factura. Se transmite el importe y, cuando el proveedor lo permite, una referencia genérica al producto. El proveedor y tu wallet pueden procesar datos técnicos de red según sus propias políticas. El juego no solicita, almacena ni transmite claves privadas, seed phrases o credenciales de tu wallet."},
			{"title": "4. RANKINGS Y SERVICIOS ONLINE", "body": "En esta compilación el servicio de ranking online está desactivado por defecto. Si se habilita en una versión futura, el juego podrá enviar un alias seudónimo, el identificador aleatorio de instalación, la clave del desafío, movimientos, tiempo, eficiencia, recorrido y versión de la app para publicar resultados. La política deberá mantenerse actualizada si cambia este tratamiento."},
			{"title": "5. ANALÍTICA, PUBLICIDAD Y PERMISOS", "body": "Esta versión no integra SDKs propios de publicidad ni analítica de terceros. Usa acceso a Internet para pagos Lightning y, si se configura, servicios de ranking. La tienda, el sistema operativo, la wallet o el proveedor de pagos pueden procesar información de acuerdo con sus propias políticas, fuera del control de ILLU ENTERTAINMENT."},
			{"title": "6. CONSERVACIÓN Y ELIMINACIÓN", "body": "Los datos de juego permanecen en el almacenamiento local hasta que borres los datos de la aplicación o la desinstales, sujeto al comportamiento del sistema operativo. Las compras Lightning pueden no restaurarse al cambiar de dispositivo o borrar la app porque esta versión no usa una cuenta ni un servidor de restauración. Los terceros de pago conservan sus propios registros según sus políticas y obligaciones legales."},
			{"title": "7. MENORES", "body": "Satoshi Maze no está diseñado para solicitar datos personales de menores. Las compras deben realizarse únicamente por una persona autorizada a usar la wallet correspondiente y, cuando la ley lo requiera, con autorización de madre, padre o tutor."},
			{"title": "8. SEGURIDAD", "body": "Las comunicaciones de pago exigidas por la app utilizan HTTPS y el contenido solo se desbloquea después de una verificación automática del invoice. Ningún sistema es absolutamente seguro; mantené tu dispositivo y tu wallet protegidos y nunca compartas claves privadas ni frases semilla."},
			{"title": "9. CAMBIOS Y TUS DERECHOS", "body": "Podemos actualizar esta política cuando cambien las funciones, proveedores o requisitos legales. La fecha de vigencia se actualizará con los cambios. Los derechos obligatorios previstos por las leyes de privacidad y protección al consumidor aplicables no se limitan por esta política."},
		],
		"terms_title": "TÉRMINOS Y CONDICIONES DE USO",
		"terms_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nVigente desde: 11/09/2026",
		"terms_sections": [
			{"title": "1. ACEPTACIÓN", "body": "Al instalar o usar Satoshi Maze aceptás estos términos. Si no estás de acuerdo, no utilices la aplicación ni realices compras. Los derechos obligatorios que te otorgue la legislación aplicable siguen vigentes."},
			{"title": "2. LICENCIA DE USO", "body": "ILLU ENTERTAINMENT te concede una licencia personal, limitada, revocable, no exclusiva y no transferible para usar el juego con fines personales y lícitos. El juego, su diseño, código, gráficos, marca y contenido siguen siendo propiedad de sus respectivos titulares."},
			{"title": "3. JUEGO Y CONTENIDO VIRTUAL", "body": "El progreso, niveles, skins, trails, temas, efectos y demás elementos son contenido digital del juego. No representan dinero, depósitos, inversiones ni activos financieros, no generan rendimientos y no tienen valor de retiro dentro de Satoshi Maze."},
			{"title": "4. COMPRAS CON LIGHTNING", "body": "Los precios se muestran en satoshis antes de pagar. Una compra se acredita únicamente cuando el juego verifica automáticamente el invoice. Tu wallet o la red pueden aplicar condiciones o costos propios. No envíes sats si la aplicación indica que no puede verificar el pago."},
			{"title": "5. PERSISTENCIA Y RESTAURACIÓN", "body": "Los desbloqueos de esta versión se registran localmente en el dispositivo. Si borrás los datos, desinstalás la aplicación o cambiás de teléfono, puede no ser posible restaurarlos automáticamente. Conservá esta limitación en cuenta antes de comprar."},
			{"title": "6. REEMBOLSOS Y DERECHOS DEL CONSUMIDOR", "body": "Los pagos Lightning liquidados pueden ser técnicamente irreversibles. Esto no elimina ningún derecho obligatorio de reembolso, garantía o protección al consumidor que resulte aplicable. Ante un cobro incorrecto o un problema de acreditación, utilizá el canal de soporte indicado en la ficha oficial de la tienda."},
			{"title": "7. USO ACEPTABLE", "body": "No uses el juego para fraude, abuso, manipulación de rankings, explotación maliciosa de vulnerabilidades, interferencia con servicios o actividades ilegales. Las restricciones sobre ingeniería inversa se aplican únicamente en la medida permitida por la ley."},
			{"title": "8. SERVICIOS DE TERCEROS", "body": "Los pagos dependen de la red Lightning, tu wallet y proveedores externos. Las funciones online opcionales pueden depender de otros servicios. ILLU ENTERTAINMENT no controla su disponibilidad, tarifas, políticas ni interrupciones."},
			{"title": "9. DISPONIBILIDAD Y CAMBIOS", "body": "Podemos corregir errores, equilibrar el juego, añadir o retirar funciones y actualizar contenido. Intentaremos preservar razonablemente los desbloqueos locales, pero no se garantiza disponibilidad permanente de servicios online o de terceros."},
			{"title": "10. RESPONSABILIDAD", "body": "La aplicación se ofrece con el nivel de cuidado exigido por la ley aplicable. En la máxima medida permitida por esa ley, ILLU ENTERTAINMENT no responde por pérdidas indirectas derivadas de fallos de terceros, wallets, conectividad o uso no autorizado del dispositivo. Nada de esto excluye responsabilidades que legalmente no puedan excluirse."},
			{"title": "11. MENORES Y AUTORIZACIÓN DE PAGO", "body": "Quien realiza una compra declara estar autorizado a usar la wallet correspondiente. Las personas menores deben contar con la autorización de un adulto responsable cuando sea exigida por la legislación aplicable."},
			{"title": "12. CAMBIOS EN ESTOS TÉRMINOS", "body": "Podemos actualizar estos términos cuando cambie el juego o la normativa. La fecha de vigencia se mostrará arriba. Si un cambio exige un consentimiento específico por ley, se solicitará de la forma correspondiente."},
		],
	},
	"en": {
		"privacy_title": "PRIVACY POLICY",
		"privacy_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nEffective: September 11, 2026",
		"privacy_sections": [
			{"title": "1. CONTROLLER AND SCOPE", "body": "ILLU ENTERTAINMENT develops Satoshi Maze. This policy explains what information this version of the app handles and how it is used. For privacy questions, use the support channel listed on the official store page from which you downloaded the app."},
			{"title": "2. DATA STORED ON YOUR DEVICE", "body": "The game stores progress, stars, records, Ghost Runs, settings, language, statistics, cosmetics, owned products and local purchase history on your device. It also creates a random installation identifier for profile and leaderboard features. This identifier is not derived from your IMEI, phone number, contacts or other system identifiers."},
			{"title": "3. LIGHTNING PAYMENTS", "body": "When you start a purchase, Satoshi Maze communicates over HTTPS with the configured Lightning/LNURL-pay provider to create and verify an invoice. The amount and, when permitted by the provider, a generic product reference are sent. The provider and your wallet may process technical network data under their own policies. The game does not request, store or transmit private keys, seed phrases or wallet credentials."},
			{"title": "4. LEADERBOARDS AND ONLINE SERVICES", "body": "In this build, the online leaderboard service is disabled by default. If enabled in a future build, the game may send a pseudonymous alias, random installation identifier, challenge key, moves, time, efficiency, route and app version to publish scores. This policy must be updated if that processing changes."},
			{"title": "5. ANALYTICS, ADS AND PERMISSIONS", "body": "This version does not integrate our own advertising SDKs or third-party analytics SDKs. Internet access is used for Lightning payments and, if configured, leaderboard services. The app store, operating system, wallet or payment provider may process information under their own policies, outside ILLU ENTERTAINMENT's control."},
			{"title": "6. RETENTION AND DELETION", "body": "Game data remains in local app storage until you clear app data or uninstall the app, subject to operating-system behavior. Lightning purchases may not be restorable after changing devices or deleting the app because this version has no account or restoration server. Payment third parties retain their own records under their policies and legal obligations."},
			{"title": "7. CHILDREN", "body": "Satoshi Maze is not designed to request personal information from children. Purchases must only be made by a person authorized to use the relevant wallet and, where required by law, with permission from a parent or guardian."},
			{"title": "8. SECURITY", "body": "Payment communications required by the app use HTTPS and content is unlocked only after automatic invoice verification. No system is completely secure; keep your device and wallet protected and never share private keys or seed phrases."},
			{"title": "9. CHANGES AND YOUR RIGHTS", "body": "We may update this policy when features, providers or legal requirements change. The effective date will be updated. Mandatory rights under applicable privacy and consumer-protection laws are not limited by this policy."},
		],
		"terms_title": "TERMS AND CONDITIONS OF USE",
		"terms_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nEffective: September 11, 2026",
		"terms_sections": [
			{"title": "1. ACCEPTANCE", "body": "By installing or using Satoshi Maze you agree to these terms. If you do not agree, do not use the app or make purchases. Mandatory rights granted by applicable law remain in force."},
			{"title": "2. LICENSE", "body": "ILLU ENTERTAINMENT grants you a personal, limited, revocable, non-exclusive and non-transferable license to use the game for lawful personal purposes. The game, design, code, graphics, brand and content remain the property of their respective owners."},
			{"title": "3. GAME AND VIRTUAL CONTENT", "body": "Progress, levels, skins, trails, themes, effects and other items are digital game content. They are not money, deposits, investments or financial assets, do not generate returns, and have no withdrawal value inside Satoshi Maze."},
			{"title": "4. LIGHTNING PURCHASES", "body": "Prices are shown in satoshis before payment. A purchase is credited only after the game automatically verifies the invoice. Your wallet or network may apply its own terms or costs. Do not send sats if the app says it cannot verify the payment."},
			{"title": "5. PERSISTENCE AND RESTORATION", "body": "Unlocks in this version are recorded locally on the device. If you clear app data, uninstall the app or change phones, automatic restoration may not be possible. Consider this limitation before purchasing."},
			{"title": "6. REFUNDS AND CONSUMER RIGHTS", "body": "Settled Lightning payments may be technically irreversible. This does not remove any mandatory refund, warranty or consumer-protection rights that apply to you. For an incorrect charge or crediting issue, use the support channel listed on the official store page."},
			{"title": "7. ACCEPTABLE USE", "body": "Do not use the game for fraud, abuse, leaderboard manipulation, malicious exploitation of vulnerabilities, service interference or unlawful activity. Restrictions on reverse engineering apply only to the extent permitted by law."},
			{"title": "8. THIRD-PARTY SERVICES", "body": "Payments depend on the Lightning Network, your wallet and external providers. Optional online features may rely on other services. ILLU ENTERTAINMENT does not control their availability, fees, policies or interruptions."},
			{"title": "9. AVAILABILITY AND CHANGES", "body": "We may fix bugs, balance the game, add or remove features and update content. We will reasonably try to preserve local unlocks, but permanent availability of online or third-party services is not guaranteed."},
			{"title": "10. LIABILITY", "body": "The app is provided with the level of care required by applicable law. To the maximum extent permitted by that law, ILLU ENTERTAINMENT is not liable for indirect losses caused by third-party failures, wallets, connectivity or unauthorized device use. Nothing excludes liability that cannot legally be excluded."},
			{"title": "11. MINORS AND PAYMENT AUTHORIZATION", "body": "Anyone making a purchase represents that they are authorized to use the relevant wallet. Minors must have permission from a responsible adult where required by applicable law."},
			{"title": "12. CHANGES TO THESE TERMS", "body": "We may update these terms when the game or applicable rules change. The effective date is shown above. If a change legally requires specific consent, it will be requested in the appropriate manner."},
		],
	},
	"pt": {
		"privacy_title": "POLÍTICA DE PRIVACIDADE",
		"privacy_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nVigente desde: 11/09/2026",
		"privacy_sections": [
			{"title": "1. RESPONSÁVEL E ESCOPO", "body": "ILLU ENTERTAINMENT desenvolve Satoshi Maze. Esta política explica quais informações esta versão do aplicativo trata e como elas são usadas. Para questões de privacidade, use o canal de suporte publicado na página oficial da loja onde você baixou o aplicativo."},
			{"title": "2. DADOS ARMAZENADOS NO DISPOSITIVO", "body": "O jogo salva localmente progresso, estrelas, recordes, Ghost Runs, configurações, idioma, estatísticas, cosméticos, produtos adquiridos e histórico local de compras. Também gera um identificador aleatório de instalação para perfil e ranking. Ele não é derivado de IMEI, número de telefone, contatos ou outros identificadores do sistema."},
			{"title": "3. PAGAMENTOS LIGHTNING", "body": "Ao iniciar uma compra, Satoshi Maze se comunica por HTTPS com o provedor Lightning/LNURL-pay configurado para criar e verificar uma invoice. São enviados o valor e, quando permitido pelo provedor, uma referência genérica ao produto. O provedor e sua wallet podem tratar dados técnicos de rede conforme suas próprias políticas. O jogo não solicita, armazena nem transmite chaves privadas, seed phrases ou credenciais da wallet."},
			{"title": "4. RANKINGS E SERVIÇOS ONLINE", "body": "Nesta compilação, o ranking online fica desativado por padrão. Se for ativado no futuro, o jogo poderá enviar alias pseudônimo, identificador aleatório de instalação, chave do desafio, movimentos, tempo, eficiência, percurso e versão do app para publicar resultados. Esta política deverá ser atualizada se esse tratamento mudar."},
			{"title": "5. ANALÍTICA, ANÚNCIOS E PERMISSÕES", "body": "Esta versão não integra SDKs próprios de publicidade nem SDKs de analítica de terceiros. O acesso à Internet é usado para pagamentos Lightning e, se configurado, ranking. Loja, sistema operacional, wallet ou provedor de pagamentos podem tratar informações segundo suas próprias políticas, fora do controle da ILLU ENTERTAINMENT."},
			{"title": "6. RETENÇÃO E EXCLUSÃO", "body": "Os dados do jogo permanecem no armazenamento local até você limpar os dados do app ou desinstalá-lo, conforme o comportamento do sistema. Compras Lightning podem não ser restauradas após trocar de aparelho ou apagar o app porque esta versão não usa conta nem servidor de restauração. Terceiros de pagamento mantêm seus próprios registros conforme políticas e obrigações legais."},
			{"title": "7. MENORES", "body": "Satoshi Maze não foi projetado para solicitar dados pessoais de menores. Compras devem ser feitas apenas por pessoa autorizada a usar a wallet correspondente e, quando exigido por lei, com autorização de responsável."},
			{"title": "8. SEGURANÇA", "body": "As comunicações de pagamento exigidas pelo app usam HTTPS e o conteúdo só é liberado após verificação automática da invoice. Nenhum sistema é totalmente seguro; proteja seu aparelho e sua wallet e nunca compartilhe chaves privadas ou seed phrases."},
			{"title": "9. ALTERAÇÕES E DIREITOS", "body": "Podemos atualizar esta política quando recursos, provedores ou requisitos legais mudarem. A data de vigência será atualizada. Direitos obrigatórios previstos por leis aplicáveis de privacidade e defesa do consumidor não são limitados por esta política."},
		],
		"terms_title": "TERMOS E CONDIÇÕES DE USO",
		"terms_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nVigente desde: 11/09/2026",
		"terms_sections": [
			{"title": "1. ACEITAÇÃO", "body": "Ao instalar ou usar Satoshi Maze, você aceita estes termos. Se não concordar, não use o app nem faça compras. Direitos obrigatórios previstos na lei aplicável permanecem válidos."},
			{"title": "2. LICENÇA", "body": "ILLU ENTERTAINMENT concede uma licença pessoal, limitada, revogável, não exclusiva e intransferível para uso lícito e pessoal do jogo. O jogo, design, código, gráficos, marca e conteúdo permanecem propriedade de seus respectivos titulares."},
			{"title": "3. JOGO E CONTEÚDO VIRTUAL", "body": "Progresso, níveis, skins, trails, temas, efeitos e outros itens são conteúdo digital do jogo. Não são dinheiro, depósitos, investimentos ou ativos financeiros, não geram rendimento e não possuem valor de saque dentro de Satoshi Maze."},
			{"title": "4. COMPRAS LIGHTNING", "body": "Os preços são exibidos em satoshis antes do pagamento. A compra só é creditada após verificação automática da invoice. Sua wallet ou a rede podem aplicar condições ou custos próprios. Não envie sats se o app disser que não pode verificar o pagamento."},
			{"title": "5. PERSISTÊNCIA E RESTAURAÇÃO", "body": "Os desbloqueios desta versão são registrados localmente. Ao limpar dados, desinstalar o app ou trocar de telefone, a restauração automática pode não ser possível. Considere essa limitação antes de comprar."},
			{"title": "6. REEMBOLSOS E DIREITOS DO CONSUMIDOR", "body": "Pagamentos Lightning liquidados podem ser tecnicamente irreversíveis. Isso não elimina direitos obrigatórios de reembolso, garantia ou defesa do consumidor aplicáveis. Em caso de cobrança incorreta ou falha de crédito, use o canal de suporte da página oficial da loja."},
			{"title": "7. USO ACEITÁVEL", "body": "Não use o jogo para fraude, abuso, manipulação de rankings, exploração maliciosa de vulnerabilidades, interferência em serviços ou atividade ilegal. Restrições à engenharia reversa aplicam-se apenas na medida permitida por lei."},
			{"title": "8. SERVIÇOS DE TERCEIROS", "body": "Pagamentos dependem da Lightning Network, da sua wallet e de provedores externos. Recursos online opcionais podem depender de outros serviços. ILLU ENTERTAINMENT não controla disponibilidade, tarifas, políticas ou interrupções desses terceiros."},
			{"title": "9. DISPONIBILIDADE E ALTERAÇÕES", "body": "Podemos corrigir erros, balancear o jogo, adicionar ou remover recursos e atualizar conteúdo. Tentaremos preservar razoavelmente os desbloqueios locais, mas não garantimos disponibilidade permanente de serviços online ou de terceiros."},
			{"title": "10. RESPONSABILIDADE", "body": "O app é oferecido com o cuidado exigido pela lei aplicável. Na máxima medida permitida, ILLU ENTERTAINMENT não responde por perdas indiretas causadas por falhas de terceiros, wallets, conectividade ou uso não autorizado do aparelho. Nada exclui responsabilidades que a lei proíba excluir."},
			{"title": "11. MENORES E AUTORIZAÇÃO", "body": "Quem realiza uma compra declara estar autorizado a usar a wallet correspondente. Menores devem ter autorização de um adulto responsável quando exigido pela lei aplicável."},
			{"title": "12. ALTERAÇÕES DESTES TERMOS", "body": "Podemos atualizar estes termos quando o jogo ou as regras aplicáveis mudarem. A data de vigência aparece acima. Se a lei exigir consentimento específico, ele será solicitado de forma apropriada."},
		],
	},
	"fr": {
		"privacy_title": "POLITIQUE DE CONFIDENTIALITÉ",
		"privacy_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nEn vigueur : 11/09/2026",
		"privacy_sections": [
			{"title": "1. RESPONSABLE ET PORTÉE", "body": "ILLU ENTERTAINMENT développe Satoshi Maze. Cette politique explique les informations traitées par cette version de l’application et leur utilisation. Pour toute question de confidentialité, utilisez le canal d’assistance indiqué sur la page officielle de la boutique depuis laquelle vous avez téléchargé l’application."},
			{"title": "2. DONNÉES STOCKÉES SUR L’APPAREIL", "body": "Le jeu stocke localement la progression, les étoiles, records, Ghost Runs, réglages, langue, statistiques, cosmétiques, produits acquis et historique local des achats. Il crée aussi un identifiant d’installation aléatoire pour le profil et le classement. Cet identifiant ne provient pas de l’IMEI, du numéro de téléphone, des contacts ou d’autres identifiants système."},
			{"title": "3. PAIEMENTS LIGHTNING", "body": "Lors d’un achat, Satoshi Maze communique en HTTPS avec le fournisseur Lightning/LNURL-pay configuré afin de créer et vérifier une facture. Le montant et, si le fournisseur l’autorise, une référence générique au produit sont transmis. Le fournisseur et votre wallet peuvent traiter des données techniques réseau selon leurs propres politiques. Le jeu ne demande, ne stocke et ne transmet aucune clé privée, seed phrase ou identifiant de wallet."},
			{"title": "4. CLASSEMENTS ET SERVICES EN LIGNE", "body": "Dans cette version, le classement en ligne est désactivé par défaut. S’il est activé ultérieurement, le jeu pourra envoyer un alias pseudonyme, l’identifiant d’installation aléatoire, la clé du défi, les mouvements, le temps, l’efficacité, le parcours et la version de l’app pour publier les scores. Cette politique devra être mise à jour si ce traitement change."},
			{"title": "5. ANALYTIQUE, PUBLICITÉ ET AUTORISATIONS", "body": "Cette version n’intègre pas de SDK publicitaire propre ni de SDK analytique tiers. Internet est utilisé pour les paiements Lightning et, si configurés, les classements. La boutique, le système, la wallet ou le fournisseur de paiement peuvent traiter des informations selon leurs propres politiques, hors du contrôle d’ILLU ENTERTAINMENT."},
			{"title": "6. CONSERVATION ET SUPPRESSION", "body": "Les données du jeu restent dans le stockage local jusqu’à la suppression des données de l’app ou sa désinstallation, selon le comportement du système. Les achats Lightning peuvent ne pas être restaurables après changement d’appareil ou suppression de l’app car cette version n’utilise ni compte ni serveur de restauration. Les tiers de paiement conservent leurs propres données selon leurs politiques et obligations légales."},
			{"title": "7. MINEURS", "body": "Satoshi Maze n’est pas conçu pour demander des données personnelles aux mineurs. Les achats doivent être effectués uniquement par une personne autorisée à utiliser la wallet concernée et, lorsque la loi l’exige, avec l’autorisation d’un parent ou tuteur."},
			{"title": "8. SÉCURITÉ", "body": "Les communications de paiement requises utilisent HTTPS et le contenu n’est débloqué qu’après vérification automatique de la facture. Aucun système n’est totalement sûr ; protégez votre appareil et votre wallet et ne partagez jamais de clés privées ni de seed phrases."},
			{"title": "9. MODIFICATIONS ET VOS DROITS", "body": "Nous pouvons mettre à jour cette politique lorsque les fonctions, fournisseurs ou exigences légales changent. La date d’entrée en vigueur sera mise à jour. Les droits obligatoires prévus par les lois applicables sur la vie privée et la protection des consommateurs ne sont pas limités par cette politique."},
		],
		"terms_title": "CONDITIONS GÉNÉRALES D’UTILISATION",
		"terms_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nEn vigueur : 11/09/2026",
		"terms_sections": [
			{"title": "1. ACCEPTATION", "body": "En installant ou utilisant Satoshi Maze, vous acceptez ces conditions. Si vous n’êtes pas d’accord, n’utilisez pas l’application et n’effectuez pas d’achat. Les droits obligatoires accordés par la loi applicable restent en vigueur."},
			{"title": "2. LICENCE", "body": "ILLU ENTERTAINMENT vous accorde une licence personnelle, limitée, révocable, non exclusive et non transférable pour un usage personnel et licite du jeu. Le jeu, son design, son code, ses graphismes, sa marque et son contenu restent la propriété de leurs titulaires respectifs."},
			{"title": "3. JEU ET CONTENU VIRTUEL", "body": "Progression, niveaux, skins, trails, thèmes, effets et autres éléments sont du contenu numérique du jeu. Ils ne constituent ni argent, ni dépôt, ni investissement, ni actif financier, ne produisent aucun rendement et n’ont aucune valeur de retrait dans Satoshi Maze."},
			{"title": "4. ACHATS LIGHTNING", "body": "Les prix sont affichés en satoshis avant paiement. Un achat n’est crédité qu’après vérification automatique de la facture. Votre wallet ou le réseau peuvent appliquer leurs propres conditions ou frais. N’envoyez pas de sats si l’application indique qu’elle ne peut pas vérifier le paiement."},
			{"title": "5. CONSERVATION ET RESTAURATION", "body": "Les déblocages de cette version sont enregistrés localement. Si vous effacez les données, désinstallez l’app ou changez de téléphone, une restauration automatique peut être impossible. Tenez compte de cette limite avant tout achat."},
			{"title": "6. REMBOURSEMENTS ET DROITS DU CONSOMMATEUR", "body": "Les paiements Lightning réglés peuvent être techniquement irréversibles. Cela ne supprime aucun droit obligatoire de remboursement, garantie ou protection du consommateur qui vous est applicable. En cas de débit incorrect ou de problème de crédit, utilisez le canal d’assistance de la page officielle de la boutique."},
			{"title": "7. UTILISATION ACCEPTABLE", "body": "N’utilisez pas le jeu à des fins de fraude, abus, manipulation des classements, exploitation malveillante de vulnérabilités, perturbation de services ou activité illégale. Les restrictions d’ingénierie inverse ne s’appliquent que dans la mesure autorisée par la loi."},
			{"title": "8. SERVICES TIERS", "body": "Les paiements dépendent du Lightning Network, de votre wallet et de fournisseurs externes. Les fonctions en ligne optionnelles peuvent dépendre d’autres services. ILLU ENTERTAINMENT ne contrôle pas leur disponibilité, tarifs, politiques ou interruptions."},
			{"title": "9. DISPONIBILITÉ ET MODIFICATIONS", "body": "Nous pouvons corriger des bugs, équilibrer le jeu, ajouter ou retirer des fonctions et mettre à jour le contenu. Nous essaierons raisonnablement de préserver les déblocages locaux, sans garantir la disponibilité permanente des services en ligne ou tiers."},
			{"title": "10. RESPONSABILITÉ", "body": "L’application est fournie avec le niveau de diligence exigé par la loi applicable. Dans la mesure maximale permise, ILLU ENTERTAINMENT n’est pas responsable des pertes indirectes dues aux défaillances de tiers, wallets, connectivité ou usage non autorisé de l’appareil. Rien n’exclut une responsabilité qui ne peut légalement être exclue."},
			{"title": "11. MINEURS ET AUTORISATION DE PAIEMENT", "body": "Toute personne effectuant un achat déclare être autorisée à utiliser la wallet concernée. Les mineurs doivent obtenir l’autorisation d’un adulte responsable lorsque la loi applicable l’exige."},
			{"title": "12. MODIFICATION DES CONDITIONS", "body": "Nous pouvons mettre à jour ces conditions si le jeu ou les règles applicables changent. La date d’entrée en vigueur figure ci-dessus. Si la loi exige un consentement spécifique, il sera demandé de manière appropriée."},
		],
	},
	"de": {
		"privacy_title": "DATENSCHUTZERKLÄRUNG",
		"privacy_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nGültig ab: 11.09.2026",
		"privacy_sections": [
			{"title": "1. VERANTWORTLICHER UND GELTUNGSBEREICH", "body": "ILLU ENTERTAINMENT entwickelt Satoshi Maze. Diese Erklärung beschreibt, welche Informationen diese App-Version verarbeitet und wie sie verwendet werden. Für Datenschutzfragen nutze den Support-Kanal auf der offiziellen Store-Seite, von der du die App heruntergeladen hast."},
			{"title": "2. AUF DEM GERÄT GESPEICHERTE DATEN", "body": "Das Spiel speichert Fortschritt, Sterne, Rekorde, Ghost Runs, Einstellungen, Sprache, Statistiken, Kosmetik, erworbene Produkte und lokale Kaufhistorie auf deinem Gerät. Zusätzlich wird eine zufällige Installations-ID für Profil- und Ranglistenfunktionen erzeugt. Sie wird nicht aus IMEI, Telefonnummer, Kontakten oder anderen Systemkennungen abgeleitet."},
			{"title": "3. LIGHTNING-ZAHLUNGEN", "body": "Wenn du einen Kauf startest, kommuniziert Satoshi Maze per HTTPS mit dem konfigurierten Lightning/LNURL-pay-Anbieter, um eine Rechnung zu erstellen und zu prüfen. Übertragen werden der Betrag und, sofern erlaubt, eine allgemeine Produktreferenz. Anbieter und Wallet können technische Netzwerkdaten nach ihren eigenen Richtlinien verarbeiten. Das Spiel fordert keine privaten Schlüssel, Seed-Phrases oder Wallet-Zugangsdaten an und speichert oder überträgt sie nicht."},
			{"title": "4. RANGLISTEN UND ONLINE-DIENSTE", "body": "In diesem Build ist die Online-Rangliste standardmäßig deaktiviert. Wird sie später aktiviert, kann das Spiel einen pseudonymen Alias, die zufällige Installations-ID, Challenge-Key, Züge, Zeit, Effizienz, Route und App-Version zur Veröffentlichung von Ergebnissen senden. Diese Erklärung muss bei Änderungen aktualisiert werden."},
			{"title": "5. ANALYSE, WERBUNG UND BERECHTIGUNGEN", "body": "Diese Version enthält keine eigenen Werbe-SDKs und keine Analyse-SDKs Dritter. Internetzugriff wird für Lightning-Zahlungen und, falls konfiguriert, Ranglisten verwendet. Store, Betriebssystem, Wallet oder Zahlungsanbieter können Informationen nach eigenen Richtlinien verarbeiten; dies liegt außerhalb der Kontrolle von ILLU ENTERTAINMENT."},
			{"title": "6. SPEICHERDAUER UND LÖSCHUNG", "body": "Spieldaten bleiben lokal gespeichert, bis du App-Daten löschst oder die App deinstallierst, abhängig vom Betriebssystem. Lightning-Käufe können nach Gerätewechsel oder Löschung der App möglicherweise nicht wiederhergestellt werden, da diese Version kein Konto und keinen Wiederherstellungsserver nutzt. Zahlungsanbieter bewahren eigene Datensätze nach ihren Richtlinien und gesetzlichen Pflichten auf."},
			{"title": "7. MINDERJÄHRIGE", "body": "Satoshi Maze ist nicht darauf ausgelegt, personenbezogene Daten von Minderjährigen abzufragen. Käufe dürfen nur von einer Person vorgenommen werden, die zur Nutzung der betreffenden Wallet berechtigt ist, und soweit gesetzlich erforderlich mit Zustimmung eines Erziehungsberechtigten."},
			{"title": "8. SICHERHEIT", "body": "Erforderliche Zahlungskommunikation nutzt HTTPS und Inhalte werden erst nach automatischer Invoice-Prüfung freigeschaltet. Kein System ist vollständig sicher; schütze Gerät und Wallet und teile niemals private Schlüssel oder Seed-Phrases."},
			{"title": "9. ÄNDERUNGEN UND DEINE RECHTE", "body": "Wir können diese Erklärung aktualisieren, wenn sich Funktionen, Anbieter oder rechtliche Anforderungen ändern. Das Gültigkeitsdatum wird angepasst. Zwingende Rechte aus anwendbarem Datenschutz- und Verbraucherschutzrecht werden dadurch nicht eingeschränkt."},
		],
		"terms_title": "NUTZUNGSBEDINGUNGEN",
		"terms_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nGültig ab: 11.09.2026",
		"terms_sections": [
			{"title": "1. ZUSTIMMUNG", "body": "Mit Installation oder Nutzung von Satoshi Maze stimmst du diesen Bedingungen zu. Wenn du nicht zustimmst, nutze die App nicht und tätige keine Käufe. Zwingende Rechte nach anwendbarem Recht bleiben bestehen."},
			{"title": "2. LIZENZ", "body": "ILLU ENTERTAINMENT gewährt dir eine persönliche, beschränkte, widerrufliche, nicht ausschließliche und nicht übertragbare Lizenz zur rechtmäßigen privaten Nutzung. Spiel, Design, Code, Grafiken, Marke und Inhalte bleiben Eigentum ihrer jeweiligen Rechteinhaber."},
			{"title": "3. SPIEL UND VIRTUELLE INHALTE", "body": "Fortschritt, Level, Skins, Trails, Themes, Effekte und andere Elemente sind digitale Spielinhalte. Sie sind kein Geld, keine Einlage, Investition oder Finanzanlage, erzeugen keine Rendite und haben in Satoshi Maze keinen Auszahlungswert."},
			{"title": "4. LIGHTNING-KÄUFE", "body": "Preise werden vor der Zahlung in Satoshis angezeigt. Ein Kauf wird erst nach automatischer Prüfung der Invoice gutgeschrieben. Wallet oder Netzwerk können eigene Bedingungen oder Kosten anwenden. Sende keine Sats, wenn die App meldet, dass die Zahlung nicht geprüft werden kann."},
			{"title": "5. SPEICHERUNG UND WIEDERHERSTELLUNG", "body": "Freischaltungen dieser Version werden lokal gespeichert. Nach Löschen der App-Daten, Deinstallation oder Gerätewechsel ist automatische Wiederherstellung möglicherweise nicht möglich. Berücksichtige dies vor einem Kauf."},
			{"title": "6. ERSTATTUNGEN UND VERBRAUCHERRECHTE", "body": "Abgeschlossene Lightning-Zahlungen können technisch unumkehrbar sein. Zwingende Rechte auf Erstattung, Gewährleistung oder Verbraucherschutz bleiben unberührt. Bei falscher Belastung oder fehlender Freischaltung nutze den Support-Kanal auf der offiziellen Store-Seite."},
			{"title": "7. ZULÄSSIGE NUTZUNG", "body": "Nutze das Spiel nicht für Betrug, Missbrauch, Ranglistenmanipulation, böswillige Ausnutzung von Schwachstellen, Störung von Diensten oder rechtswidrige Aktivitäten. Einschränkungen für Reverse Engineering gelten nur soweit gesetzlich zulässig."},
			{"title": "8. DIENSTE DRITTER", "body": "Zahlungen hängen vom Lightning Network, deiner Wallet und externen Anbietern ab. Optionale Online-Funktionen können weitere Dienste nutzen. ILLU ENTERTAINMENT kontrolliert deren Verfügbarkeit, Gebühren, Richtlinien oder Ausfälle nicht."},
			{"title": "9. VERFÜGBARKEIT UND ÄNDERUNGEN", "body": "Wir können Fehler beheben, das Spiel ausbalancieren, Funktionen hinzufügen oder entfernen und Inhalte aktualisieren. Lokale Freischaltungen sollen angemessen erhalten bleiben; dauerhafte Verfügbarkeit von Online- oder Drittanbieterdiensten wird nicht garantiert."},
			{"title": "10. HAFTUNG", "body": "Die App wird mit der nach anwendbarem Recht erforderlichen Sorgfalt bereitgestellt. Soweit gesetzlich zulässig, haftet ILLU ENTERTAINMENT nicht für indirekte Verluste durch Ausfälle Dritter, Wallets, Verbindungen oder unbefugte Gerätenutzung. Nicht ausschließbare gesetzliche Haftung bleibt unberührt."},
			{"title": "11. MINDERJÄHRIGE UND ZAHLUNGSBEFUGNIS", "body": "Wer einen Kauf tätigt, erklärt, zur Nutzung der betreffenden Wallet berechtigt zu sein. Minderjährige benötigen die Zustimmung eines verantwortlichen Erwachsenen, soweit gesetzlich vorgeschrieben."},
			{"title": "12. ÄNDERUNGEN DIESER BEDINGUNGEN", "body": "Wir können diese Bedingungen aktualisieren, wenn sich Spiel oder geltende Regeln ändern. Das Gültigkeitsdatum steht oben. Ist gesetzlich eine besondere Zustimmung erforderlich, wird sie entsprechend eingeholt."},
		],
	},
	"it": {
		"privacy_title": "INFORMATIVA SULLA PRIVACY",
		"privacy_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nIn vigore dal: 11/09/2026",
		"privacy_sections": [
			{"title": "1. TITOLARE E AMBITO", "body": "ILLU ENTERTAINMENT sviluppa Satoshi Maze. Questa informativa spiega quali informazioni vengono trattate da questa versione dell’app e come vengono utilizzate. Per domande sulla privacy, usa il canale di assistenza indicato nella pagina ufficiale dello store da cui hai scaricato l’app."},
			{"title": "2. DATI SALVATI SUL DISPOSITIVO", "body": "Il gioco salva localmente progressi, stelle, record, Ghost Run, impostazioni, lingua, statistiche, cosmetici, prodotti acquistati e cronologia locale degli acquisti. Genera anche un identificatore casuale di installazione per profilo e classifiche. Non deriva da IMEI, numero di telefono, contatti o altri identificatori di sistema."},
			{"title": "3. PAGAMENTI LIGHTNING", "body": "Quando avvii un acquisto, Satoshi Maze comunica tramite HTTPS con il provider Lightning/LNURL-pay configurato per creare e verificare una invoice. Vengono inviati l’importo e, se consentito, un riferimento generico al prodotto. Provider e wallet possono trattare dati tecnici di rete secondo le proprie informative. Il gioco non richiede, memorizza o trasmette chiavi private, seed phrase o credenziali della wallet."},
			{"title": "4. CLASSIFICHE E SERVIZI ONLINE", "body": "In questa build la classifica online è disattivata per impostazione predefinita. Se verrà attivata in futuro, il gioco potrà inviare alias pseudonimo, identificatore casuale di installazione, chiave della sfida, mosse, tempo, efficienza, percorso e versione dell’app per pubblicare i risultati. L’informativa dovrà essere aggiornata se questo trattamento cambia."},
			{"title": "5. ANALITICA, PUBBLICITÀ E PERMESSI", "body": "Questa versione non integra SDK pubblicitari propri né SDK analitici di terze parti. L’accesso a Internet è usato per pagamenti Lightning e, se configurate, classifiche. Store, sistema operativo, wallet o provider di pagamento possono trattare informazioni secondo le proprie politiche, fuori dal controllo di ILLU ENTERTAINMENT."},
			{"title": "6. CONSERVAZIONE E CANCELLAZIONE", "body": "I dati di gioco restano nello storage locale finché non cancelli i dati dell’app o la disinstalli, secondo il comportamento del sistema. Gli acquisti Lightning potrebbero non essere ripristinabili dopo cambio dispositivo o cancellazione dell’app perché questa versione non usa account né server di ripristino. I terzi di pagamento conservano i propri dati secondo politiche e obblighi di legge."},
			{"title": "7. MINORI", "body": "Satoshi Maze non è progettato per richiedere dati personali ai minori. Gli acquisti devono essere effettuati solo da chi è autorizzato a usare la wallet e, quando richiesto dalla legge, con il consenso di un genitore o tutore."},
			{"title": "8. SICUREZZA", "body": "Le comunicazioni di pagamento richieste dall’app usano HTTPS e i contenuti vengono sbloccati solo dopo la verifica automatica della invoice. Nessun sistema è completamente sicuro; proteggi dispositivo e wallet e non condividere mai chiavi private o seed phrase."},
			{"title": "9. MODIFICHE E DIRITTI", "body": "Possiamo aggiornare questa informativa quando cambiano funzioni, provider o requisiti di legge. La data di efficacia verrà aggiornata. I diritti obbligatori previsti dalle leggi applicabili su privacy e tutela dei consumatori non vengono limitati da questa informativa."},
		],
		"terms_title": "TERMINI E CONDIZIONI D’USO",
		"terms_intro": "Satoshi Maze · ILLU ENTERTAINMENT\nIn vigore dal: 11/09/2026",
		"terms_sections": [
			{"title": "1. ACCETTAZIONE", "body": "Installando o usando Satoshi Maze accetti questi termini. Se non accetti, non usare l’app e non effettuare acquisti. I diritti obbligatori previsti dalla legge applicabile restano validi."},
			{"title": "2. LICENZA", "body": "ILLU ENTERTAINMENT ti concede una licenza personale, limitata, revocabile, non esclusiva e non trasferibile per uso personale e lecito del gioco. Gioco, design, codice, grafica, marchio e contenuti restano di proprietà dei rispettivi titolari."},
			{"title": "3. GIOCO E CONTENUTI VIRTUALI", "body": "Progressi, livelli, skin, trail, temi, effetti e altri elementi sono contenuti digitali del gioco. Non sono denaro, depositi, investimenti o attività finanziarie, non generano rendimenti e non hanno valore di prelievo dentro Satoshi Maze."},
			{"title": "4. ACQUISTI LIGHTNING", "body": "I prezzi sono mostrati in satoshi prima del pagamento. Un acquisto viene accreditato solo dopo la verifica automatica della invoice. Wallet o rete possono applicare condizioni o costi propri. Non inviare sats se l’app indica che non può verificare il pagamento."},
			{"title": "5. PERSISTENZA E RIPRISTINO", "body": "Gli sblocchi di questa versione sono registrati localmente. Se cancelli i dati, disinstalli l’app o cambi telefono, il ripristino automatico potrebbe non essere possibile. Considera questa limitazione prima di acquistare."},
			{"title": "6. RIMBORSI E DIRITTI DEL CONSUMATORE", "body": "I pagamenti Lightning regolati possono essere tecnicamente irreversibili. Ciò non elimina diritti obbligatori di rimborso, garanzia o tutela del consumatore applicabili. Per addebiti errati o problemi di accredito, usa il canale di assistenza indicato nella pagina ufficiale dello store."},
			{"title": "7. USO ACCETTABILE", "body": "Non usare il gioco per frode, abuso, manipolazione delle classifiche, sfruttamento malevolo di vulnerabilità, interferenza con servizi o attività illegali. Le restrizioni sul reverse engineering si applicano solo nella misura consentita dalla legge."},
			{"title": "8. SERVIZI DI TERZE PARTI", "body": "I pagamenti dipendono da Lightning Network, dalla tua wallet e da provider esterni. Le funzioni online opzionali possono dipendere da altri servizi. ILLU ENTERTAINMENT non controlla disponibilità, tariffe, politiche o interruzioni di tali terzi."},
			{"title": "9. DISPONIBILITÀ E MODIFICHE", "body": "Possiamo correggere bug, bilanciare il gioco, aggiungere o rimuovere funzioni e aggiornare contenuti. Cercheremo ragionevolmente di preservare gli sblocchi locali, ma non garantiamo disponibilità permanente dei servizi online o di terze parti."},
			{"title": "10. RESPONSABILITÀ", "body": "L’app è fornita con il livello di diligenza richiesto dalla legge applicabile. Nella misura massima consentita, ILLU ENTERTAINMENT non risponde di perdite indirette causate da guasti di terzi, wallet, connettività o uso non autorizzato del dispositivo. Nulla esclude responsabilità che non possono essere escluse per legge."},
			{"title": "11. MINORI E AUTORIZZAZIONE AL PAGAMENTO", "body": "Chi effettua un acquisto dichiara di essere autorizzato a usare la wallet corrispondente. I minori devono avere l’autorizzazione di un adulto responsabile quando richiesto dalla legge applicabile."},
			{"title": "12. MODIFICHE AI TERMINI", "body": "Possiamo aggiornare questi termini quando cambiano il gioco o le norme applicabili. La data di efficacia è indicata sopra. Se la legge richiede un consenso specifico, verrà richiesto in modo appropriato."},
		],
	},
}

static func _document() -> Dictionary:
	var lang: String = Localization.current_language()
	var document: Dictionary = DOCUMENTS.get(lang, DOCUMENTS["en"])
	return document

static func privacy_title() -> String:
	return str(_document().get("privacy_title", "PRIVACY POLICY"))

static func privacy_intro() -> String:
	return str(_document().get("privacy_intro", ""))

static func privacy_sections() -> Array:
	var document: Dictionary = _document()
	var sections: Array = document.get("privacy_sections", [])
	return sections

static func terms_title() -> String:
	return str(_document().get("terms_title", "TERMS AND CONDITIONS"))

static func terms_intro() -> String:
	return str(_document().get("terms_intro", ""))

static func terms_sections() -> Array:
	var document: Dictionary = _document()
	var sections: Array = document.get("terms_sections", [])
	return sections
